package procharity.tests.registerAsFoundation;


public class EmailTestData {


    public final String emailValidLength255 = "crrirrpycprhricioirhrayhiiirpthphhorpyyotahohtiyroarrpaoocrpaociypcophrtrirttaocopiooiorcrhrhphrrpcriypathrariirhcoihtarpapiirtrciairoypccayiipyyiaoirrycpprythrtracrrittaccpaparatycoyhcicrpaocroiyhrrrtryapccrcohioticryciiirhproparrppryiaocraocpa@gmail.com";
    public final String emailValidLength254 = "crrirrpycprhricioirhrayhiiirpthphhorpyyotahohtiyrorrpaoocrpaociypcophrtrirttaocopiooiorcrhrhphrrpcriypathrariirhcoihtarpapiirtrciairoypccayiipyyiaoirrycpprythrtracrrittaccpaparatycoyhcicrpaocroiyhrrrtryapccrcohioticryciiirhproparrppryiaocraocpa@gmail.com";
    public final String emailInValidLength256 = "crrirrpycprhricioirhrayhiiirpthphhorpyyotahccohtiyroarrpaoocrpaociypcophrtrirttaocopiooiorcrhrhphrrpcriypathrariirhcoihtarpapiirtrciairoypccayiipyyiaoirrycpprythrtracrrittaccpaparatycoyhcicrpaocroiyhrrrtryapccrcohioticryciiirhproparrppryiaocraocpa@gmail.com";
    public final String emailValidLength100 = "rythrtracrrittaccpaparatycoyhcicrpaocroiyhrrrtryapccrcohioticryciiirhproparrppryiaocraocpa@gmail.com";
    public final String emailValidLength1 ="p";
    public final String emailInvalidLength0 ="";
    public final String emailInvalidLength1000 = "riahochphcrproharpoyttypcprporrtaatahrtyccpyarhrytyrproctchoytrtcocothroipchoccciytrciirchorarryippcppaititrraraiatypcryhrtotyatirohrohaaratpryttphtoccrtpcocrropootcprcparptoopctoirrcyyhchppiracirotrpooyhirhcacayrryyiictpiaytrtioctrririrptroryrahoiyariricttpyrcttyrtrrcryopirriyyyathppahrirtrroichpcitycahrriortopayipctrryooccipyraypohatiiccooayoyhcoraicyohyrrtiorrrraoptyrtaityrachrriyhaoiihriihcycprchpairyrhyparioytahrhrhihtcrhcrryoattryhaahprropoyyiohtiihyaoatraphhthoryhrrpracaharyicoaiiiyptpyahyttrarrotioaptiyrccipryiraicriarayartortayacphapypparrapciotrypacyrchrryitotyttprcirirraoryoratrtrhorccrrptyyartyrtyyraotyccyaiyyrootrhccocohhhayirhichtahtipciccrhayycrppciarrhacoaprriotprrrrtoooairihhrtiryopprhooacyyyipopotpphytyhcarrphhiaoayraapppyortriatioorcrcroiytriccarrrpioprtahriphyoroapahthhicrcroyrriicrihyyriprcypcicyrpcctrtirytraitcytrhhtirptchaoacyahcohrtioytrtyaoyipacacpphrtirtcyarcyroarcytyayrrpcayrytoprtaoihtorhyihiiaiyoaipiracrcoiparrrahtihpcaahophriypotoprratipyoriircth@gmail.com";
    public final String emailInputDigits = "1234567890";
    public final String emailInputSpecialSymbols = "!@#$%^&*()_+";
    public final String emailInputCyrillic = "Друзья";
    public final String emailInputLatin = "Friends";

}
